# if (9 < 0) and (0 < -9):
#     print("hello")
# elif (9 > 0) or False:
#     print("good")
# else:
#     print("bad")

# x = 5.2
# if (type(x) is not int):
#     print("true")
# else:
#     print("false")

# x = 24
# y = 20
# list = [10, 20, 30, 40, 50 ];
# if ( x not in list ):
#     print("x is NOT present in given list")
# else:
#     print("x is present in given list")
# if ( y in list ):
#     print("y is present in given list")

# x = 24
# y = 20
# list = [10, 20, 30, 40, 50 ]
# if ( x not in list ):
#     print("x is NOT present in given list")
# else:
#     print("x is present in given list")
# if ( y in list ):
#     print("y is present in given list")
# else:
#     print("y is NOT present in given list")